# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c548457859a25725dab488096aae468de0aae7ba87edc5655bc5851834babb02b1c7a3d7496e17fe78e22ca6b4ccfd90f66d2d8ec743970b7e44a1041478ca75

test:
  secret_key_base: cfa717c7a88bf28159835dca98322efd9794ef5814955a064653b1c9020fb8ae093b1ad4d58edf55c2ab0b44229186cfe5ec7d3f82c8f7df481f67b9a29f0eab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
